// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import java.lang.String;

privileged aspect UserAccount_Roo_JavaBean {
    
    public String UserAccount.getName() {
        return this.name;
    }
    
    public void UserAccount.setName(String name) {
        this.name = name;
    }
    
}
