// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.Employer;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect EmployerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployerDataOnDemand: @Component;
    
    private Random EmployerDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Employer> EmployerDataOnDemand.data;
    
    public Employer EmployerDataOnDemand.getNewTransientEmployer(int index) {
        edu.unlv.cs.rebelhotel.domain.Employer obj = new edu.unlv.cs.rebelhotel.domain.Employer();
        obj.setLocation("location_" + index);
        return obj;
    }
    
    public Employer EmployerDataOnDemand.getSpecificEmployer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Employer obj = data.get(index);
        return Employer.findEmployer(obj.getId());
    }
    
    public Employer EmployerDataOnDemand.getRandomEmployer() {
        init();
        Employer obj = data.get(rnd.nextInt(data.size()));
        return Employer.findEmployer(obj.getId());
    }
    
    public boolean EmployerDataOnDemand.modifyEmployer(Employer obj) {
        return false;
    }
    
    public void EmployerDataOnDemand.init() {
        data = edu.unlv.cs.rebelhotel.domain.Employer.findEmployerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Employer' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.unlv.cs.rebelhotel.domain.Employer>();
        for (int i = 0; i < 10; i++) {
            edu.unlv.cs.rebelhotel.domain.Employer obj = getNewTransientEmployer(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
