// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.EmployerDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EmployerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EmployerIntegrationTest: @Transactional;
    
    @Autowired
    private EmployerDataOnDemand EmployerIntegrationTest.dod;
    
    @Test
    public void EmployerIntegrationTest.testCountEmployers() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", dod.getRandomEmployer());
        long count = edu.unlv.cs.rebelhotel.domain.Employer.countEmployers();
        org.junit.Assert.assertTrue("Counter for 'Employer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployerIntegrationTest.testFindEmployer() {
        edu.unlv.cs.rebelhotel.domain.Employer obj = dod.getRandomEmployer();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Employer.findEmployer(id);
        org.junit.Assert.assertNotNull("Find method for 'Employer' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Employer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployerIntegrationTest.testFindAllEmployers() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", dod.getRandomEmployer());
        long count = edu.unlv.cs.rebelhotel.domain.Employer.countEmployers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Employer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.unlv.cs.rebelhotel.domain.Employer> result = edu.unlv.cs.rebelhotel.domain.Employer.findAllEmployers();
        org.junit.Assert.assertNotNull("Find all method for 'Employer' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Employer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployerIntegrationTest.testFindEmployerEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", dod.getRandomEmployer());
        long count = edu.unlv.cs.rebelhotel.domain.Employer.countEmployers();
        if (count > 20) count = 20;
        java.util.List<edu.unlv.cs.rebelhotel.domain.Employer> result = edu.unlv.cs.rebelhotel.domain.Employer.findEmployerEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Employer' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Employer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployerIntegrationTest.testFlush() {
        edu.unlv.cs.rebelhotel.domain.Employer obj = dod.getRandomEmployer();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Employer.findEmployer(id);
        org.junit.Assert.assertNotNull("Find method for 'Employer' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployer(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Employer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployerIntegrationTest.testMerge() {
        edu.unlv.cs.rebelhotel.domain.Employer obj = dod.getRandomEmployer();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Employer.findEmployer(id);
        boolean modified =  dod.modifyEmployer(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.unlv.cs.rebelhotel.domain.Employer merged = (edu.unlv.cs.rebelhotel.domain.Employer) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Employer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployerIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", dod.getRandomEmployer());
        edu.unlv.cs.rebelhotel.domain.Employer obj = dod.getNewTransientEmployer(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Employer' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Employer' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployerIntegrationTest.testRemove() {
        edu.unlv.cs.rebelhotel.domain.Employer obj = dod.getRandomEmployer();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Employer' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Employer.findEmployer(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Employer' with identifier '" + id + "'", edu.unlv.cs.rebelhotel.domain.Employer.findEmployer(id));
    }
    
}
