// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.Major;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect MajorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MajorDataOnDemand: @Component;
    
    private Random MajorDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Major> MajorDataOnDemand.data;
    
    public Major MajorDataOnDemand.getNewTransientMajor(int index) {
        edu.unlv.cs.rebelhotel.domain.Major obj = new edu.unlv.cs.rebelhotel.domain.Major();
        obj.setReachedMilestone(true);
        obj.setDepartment(null);
        obj.setCatalogTerm(null);
        return obj;
    }
    
    public Major MajorDataOnDemand.getSpecificMajor(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Major obj = data.get(index);
        return Major.findMajor(obj.getId());
    }
    
    public Major MajorDataOnDemand.getRandomMajor() {
        init();
        Major obj = data.get(rnd.nextInt(data.size()));
        return Major.findMajor(obj.getId());
    }
    
    public boolean MajorDataOnDemand.modifyMajor(Major obj) {
        return false;
    }
    
    public void MajorDataOnDemand.init() {
        data = edu.unlv.cs.rebelhotel.domain.Major.findMajorEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Major' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.unlv.cs.rebelhotel.domain.Major>();
        for (int i = 0; i < 10; i++) {
            edu.unlv.cs.rebelhotel.domain.Major obj = getNewTransientMajor(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
