// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.Rebel;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect RebelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RebelDataOnDemand: @Component;
    
    private Random RebelDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Rebel> RebelDataOnDemand.data;
    
    public Rebel RebelDataOnDemand.getNewTransientRebel(int index) {
        edu.unlv.cs.rebelhotel.domain.Rebel obj = new edu.unlv.cs.rebelhotel.domain.Rebel();
        return obj;
    }
    
    public Rebel RebelDataOnDemand.getSpecificRebel(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Rebel obj = data.get(index);
        return Rebel.findRebel(obj.getId());
    }
    
    public Rebel RebelDataOnDemand.getRandomRebel() {
        init();
        Rebel obj = data.get(rnd.nextInt(data.size()));
        return Rebel.findRebel(obj.getId());
    }
    
    public boolean RebelDataOnDemand.modifyRebel(Rebel obj) {
        return false;
    }
    
    public void RebelDataOnDemand.init() {
        data = edu.unlv.cs.rebelhotel.domain.Rebel.findRebelEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Rebel' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.unlv.cs.rebelhotel.domain.Rebel>();
        for (int i = 0; i < 10; i++) {
            edu.unlv.cs.rebelhotel.domain.Rebel obj = getNewTransientRebel(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
