// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.Supervisor;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect SupervisorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SupervisorDataOnDemand: @Component;
    
    private Random SupervisorDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Supervisor> SupervisorDataOnDemand.data;
    
    public Supervisor SupervisorDataOnDemand.getNewTransientSupervisor(int index) {
        edu.unlv.cs.rebelhotel.domain.Supervisor obj = new edu.unlv.cs.rebelhotel.domain.Supervisor();
        obj.setFirstName("firstName_" + index);
        obj.setLastName("lastName_" + index);
        obj.setEmail("email_" + index);
        obj.setTitle("title_" + index);
        return obj;
    }
    
    public Supervisor SupervisorDataOnDemand.getSpecificSupervisor(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Supervisor obj = data.get(index);
        return Supervisor.findSupervisor(obj.getId());
    }
    
    public Supervisor SupervisorDataOnDemand.getRandomSupervisor() {
        init();
        Supervisor obj = data.get(rnd.nextInt(data.size()));
        return Supervisor.findSupervisor(obj.getId());
    }
    
    public boolean SupervisorDataOnDemand.modifySupervisor(Supervisor obj) {
        return false;
    }
    
    public void SupervisorDataOnDemand.init() {
        data = edu.unlv.cs.rebelhotel.domain.Supervisor.findSupervisorEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Supervisor' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.unlv.cs.rebelhotel.domain.Supervisor>();
        for (int i = 0; i < 10; i++) {
            edu.unlv.cs.rebelhotel.domain.Supervisor obj = getNewTransientSupervisor(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
