// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.SupervisorDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SupervisorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SupervisorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SupervisorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SupervisorIntegrationTest: @Transactional;
    
    @Autowired
    private SupervisorDataOnDemand SupervisorIntegrationTest.dod;
    
    @Test
    public void SupervisorIntegrationTest.testCountSupervisors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", dod.getRandomSupervisor());
        long count = edu.unlv.cs.rebelhotel.domain.Supervisor.countSupervisors();
        org.junit.Assert.assertTrue("Counter for 'Supervisor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SupervisorIntegrationTest.testFindSupervisor() {
        edu.unlv.cs.rebelhotel.domain.Supervisor obj = dod.getRandomSupervisor();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Supervisor.findSupervisor(id);
        org.junit.Assert.assertNotNull("Find method for 'Supervisor' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Supervisor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SupervisorIntegrationTest.testFindAllSupervisors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", dod.getRandomSupervisor());
        long count = edu.unlv.cs.rebelhotel.domain.Supervisor.countSupervisors();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Supervisor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.unlv.cs.rebelhotel.domain.Supervisor> result = edu.unlv.cs.rebelhotel.domain.Supervisor.findAllSupervisors();
        org.junit.Assert.assertNotNull("Find all method for 'Supervisor' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Supervisor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SupervisorIntegrationTest.testFindSupervisorEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", dod.getRandomSupervisor());
        long count = edu.unlv.cs.rebelhotel.domain.Supervisor.countSupervisors();
        if (count > 20) count = 20;
        java.util.List<edu.unlv.cs.rebelhotel.domain.Supervisor> result = edu.unlv.cs.rebelhotel.domain.Supervisor.findSupervisorEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Supervisor' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Supervisor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SupervisorIntegrationTest.testFlush() {
        edu.unlv.cs.rebelhotel.domain.Supervisor obj = dod.getRandomSupervisor();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Supervisor.findSupervisor(id);
        org.junit.Assert.assertNotNull("Find method for 'Supervisor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySupervisor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Supervisor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SupervisorIntegrationTest.testMerge() {
        edu.unlv.cs.rebelhotel.domain.Supervisor obj = dod.getRandomSupervisor();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Supervisor.findSupervisor(id);
        boolean modified =  dod.modifySupervisor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.unlv.cs.rebelhotel.domain.Supervisor merged = (edu.unlv.cs.rebelhotel.domain.Supervisor) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Supervisor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SupervisorIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", dod.getRandomSupervisor());
        edu.unlv.cs.rebelhotel.domain.Supervisor obj = dod.getNewTransientSupervisor(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Supervisor' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Supervisor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SupervisorIntegrationTest.testRemove() {
        edu.unlv.cs.rebelhotel.domain.Supervisor obj = dod.getRandomSupervisor();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Supervisor' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Supervisor.findSupervisor(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Supervisor' with identifier '" + id + "'", edu.unlv.cs.rebelhotel.domain.Supervisor.findSupervisor(id));
    }
    
}
