// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.TermDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TermIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TermIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TermIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TermIntegrationTest: @Transactional;
    
    @Autowired
    private TermDataOnDemand TermIntegrationTest.dod;
    
    @Test
    public void TermIntegrationTest.testCountTerms() {
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", dod.getRandomTerm());
        long count = edu.unlv.cs.rebelhotel.domain.Term.countTerms();
        org.junit.Assert.assertTrue("Counter for 'Term' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TermIntegrationTest.testFindTerm() {
        edu.unlv.cs.rebelhotel.domain.Term obj = dod.getRandomTerm();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Term.findTerm(id);
        org.junit.Assert.assertNotNull("Find method for 'Term' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Term' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TermIntegrationTest.testFindAllTerms() {
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", dod.getRandomTerm());
        long count = edu.unlv.cs.rebelhotel.domain.Term.countTerms();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Term', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.unlv.cs.rebelhotel.domain.Term> result = edu.unlv.cs.rebelhotel.domain.Term.findAllTerms();
        org.junit.Assert.assertNotNull("Find all method for 'Term' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Term' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TermIntegrationTest.testFindTermEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", dod.getRandomTerm());
        long count = edu.unlv.cs.rebelhotel.domain.Term.countTerms();
        if (count > 20) count = 20;
        java.util.List<edu.unlv.cs.rebelhotel.domain.Term> result = edu.unlv.cs.rebelhotel.domain.Term.findTermEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Term' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Term' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TermIntegrationTest.testFlush() {
        edu.unlv.cs.rebelhotel.domain.Term obj = dod.getRandomTerm();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Term.findTerm(id);
        org.junit.Assert.assertNotNull("Find method for 'Term' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTerm(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Term' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TermIntegrationTest.testMerge() {
        edu.unlv.cs.rebelhotel.domain.Term obj = dod.getRandomTerm();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Term.findTerm(id);
        boolean modified =  dod.modifyTerm(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.unlv.cs.rebelhotel.domain.Term merged = (edu.unlv.cs.rebelhotel.domain.Term) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Term' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TermIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", dod.getRandomTerm());
        edu.unlv.cs.rebelhotel.domain.Term obj = dod.getNewTransientTerm(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Term' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Term' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TermIntegrationTest.testRemove() {
        edu.unlv.cs.rebelhotel.domain.Term obj = dod.getRandomTerm();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Term' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.Term.findTerm(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Term' with identifier '" + id + "'", edu.unlv.cs.rebelhotel.domain.Term.findTerm(id));
    }
    
}
