// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.UserAccount;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect UserAccountDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserAccountDataOnDemand: @Component;
    
    private Random UserAccountDataOnDemand.rnd = new java.security.SecureRandom();
    
    public UserAccount UserAccountDataOnDemand.getRandomUserAccount() {
        init();
        UserAccount obj = data.get(rnd.nextInt(data.size()));
        return UserAccount.findUserAccount(obj.getId());
    }
    
    public boolean UserAccountDataOnDemand.modifyUserAccount(UserAccount obj) {
        return false;
    }
    
    public void UserAccountDataOnDemand.init() {
        data = edu.unlv.cs.rebelhotel.domain.UserAccount.findUserAccountEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'UserAccount' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.unlv.cs.rebelhotel.domain.UserAccount>();
        for (int i = 0; i < 10; i++) {
            edu.unlv.cs.rebelhotel.domain.UserAccount obj = getNewTransientUserAccount(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
