// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserAccountDataOnDemand_Roo_Configurable {
    
    declare @type: UserAccountDataOnDemand: @Configurable;
    
}
