// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.WorkTemplateDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkTemplateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkTemplateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkTemplateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: WorkTemplateIntegrationTest: @Transactional;
    
    @Autowired
    private WorkTemplateDataOnDemand WorkTemplateIntegrationTest.dod;
    
    @Test
    public void WorkTemplateIntegrationTest.testCountWorkTemplates() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", dod.getRandomWorkTemplate());
        long count = edu.unlv.cs.rebelhotel.domain.WorkTemplate.countWorkTemplates();
        org.junit.Assert.assertTrue("Counter for 'WorkTemplate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkTemplateIntegrationTest.testFindWorkTemplate() {
        edu.unlv.cs.rebelhotel.domain.WorkTemplate obj = dod.getRandomWorkTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkTemplate.findWorkTemplate(id);
        org.junit.Assert.assertNotNull("Find method for 'WorkTemplate' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'WorkTemplate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkTemplateIntegrationTest.testFindAllWorkTemplates() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", dod.getRandomWorkTemplate());
        long count = edu.unlv.cs.rebelhotel.domain.WorkTemplate.countWorkTemplates();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'WorkTemplate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.unlv.cs.rebelhotel.domain.WorkTemplate> result = edu.unlv.cs.rebelhotel.domain.WorkTemplate.findAllWorkTemplates();
        org.junit.Assert.assertNotNull("Find all method for 'WorkTemplate' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'WorkTemplate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkTemplateIntegrationTest.testFindWorkTemplateEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", dod.getRandomWorkTemplate());
        long count = edu.unlv.cs.rebelhotel.domain.WorkTemplate.countWorkTemplates();
        if (count > 20) count = 20;
        java.util.List<edu.unlv.cs.rebelhotel.domain.WorkTemplate> result = edu.unlv.cs.rebelhotel.domain.WorkTemplate.findWorkTemplateEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'WorkTemplate' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'WorkTemplate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkTemplateIntegrationTest.testFlush() {
        edu.unlv.cs.rebelhotel.domain.WorkTemplate obj = dod.getRandomWorkTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkTemplate.findWorkTemplate(id);
        org.junit.Assert.assertNotNull("Find method for 'WorkTemplate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkTemplate(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'WorkTemplate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkTemplateIntegrationTest.testMerge() {
        edu.unlv.cs.rebelhotel.domain.WorkTemplate obj = dod.getRandomWorkTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkTemplate.findWorkTemplate(id);
        boolean modified =  dod.modifyWorkTemplate(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.unlv.cs.rebelhotel.domain.WorkTemplate merged = (edu.unlv.cs.rebelhotel.domain.WorkTemplate) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'WorkTemplate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkTemplateIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", dod.getRandomWorkTemplate());
        edu.unlv.cs.rebelhotel.domain.WorkTemplate obj = dod.getNewTransientWorkTemplate(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'WorkTemplate' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'WorkTemplate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkTemplateIntegrationTest.testRemove() {
        edu.unlv.cs.rebelhotel.domain.WorkTemplate obj = dod.getRandomWorkTemplate();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkTemplate' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkTemplate.findWorkTemplate(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'WorkTemplate' with identifier '" + id + "'", edu.unlv.cs.rebelhotel.domain.WorkTemplate.findWorkTemplate(id));
    }
    
}
