// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.WorkRequirementDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkRequirementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkRequirementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkRequirementIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: WorkRequirementIntegrationTest: @Transactional;
    
    @Autowired
    private WorkRequirementDataOnDemand WorkRequirementIntegrationTest.dod;
    
    @Test
    public void WorkRequirementIntegrationTest.testCountWorkRequirements() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to initialize correctly", dod.getRandomWorkRequirement());
        long count = edu.unlv.cs.rebelhotel.domain.WorkRequirement.countWorkRequirements();
        org.junit.Assert.assertTrue("Counter for 'WorkRequirement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkRequirementIntegrationTest.testFindWorkRequirement() {
        edu.unlv.cs.rebelhotel.domain.WorkRequirement obj = dod.getRandomWorkRequirement();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkRequirement.findWorkRequirement(id);
        org.junit.Assert.assertNotNull("Find method for 'WorkRequirement' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'WorkRequirement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkRequirementIntegrationTest.testFindAllWorkRequirements() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to initialize correctly", dod.getRandomWorkRequirement());
        long count = edu.unlv.cs.rebelhotel.domain.WorkRequirement.countWorkRequirements();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'WorkRequirement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.unlv.cs.rebelhotel.domain.WorkRequirement> result = edu.unlv.cs.rebelhotel.domain.WorkRequirement.findAllWorkRequirements();
        org.junit.Assert.assertNotNull("Find all method for 'WorkRequirement' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'WorkRequirement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkRequirementIntegrationTest.testFindWorkRequirementEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to initialize correctly", dod.getRandomWorkRequirement());
        long count = edu.unlv.cs.rebelhotel.domain.WorkRequirement.countWorkRequirements();
        if (count > 20) count = 20;
        java.util.List<edu.unlv.cs.rebelhotel.domain.WorkRequirement> result = edu.unlv.cs.rebelhotel.domain.WorkRequirement.findWorkRequirementEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'WorkRequirement' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'WorkRequirement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkRequirementIntegrationTest.testFlush() {
        edu.unlv.cs.rebelhotel.domain.WorkRequirement obj = dod.getRandomWorkRequirement();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkRequirement.findWorkRequirement(id);
        org.junit.Assert.assertNotNull("Find method for 'WorkRequirement' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkRequirement(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'WorkRequirement' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkRequirementIntegrationTest.testMerge() {
        edu.unlv.cs.rebelhotel.domain.WorkRequirement obj = dod.getRandomWorkRequirement();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkRequirement.findWorkRequirement(id);
        boolean modified =  dod.modifyWorkRequirement(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.unlv.cs.rebelhotel.domain.WorkRequirement merged = (edu.unlv.cs.rebelhotel.domain.WorkRequirement) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'WorkRequirement' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkRequirementIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to initialize correctly", dod.getRandomWorkRequirement());
        edu.unlv.cs.rebelhotel.domain.WorkRequirement obj = dod.getNewTransientWorkRequirement(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'WorkRequirement' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'WorkRequirement' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'WorkRequirement' identifier to no longer be null", obj.getId());
    }
    
}
