// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.WorkTemplate;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect WorkTemplateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WorkTemplateDataOnDemand: @Component;
    
    private Random WorkTemplateDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<WorkTemplate> WorkTemplateDataOnDemand.data;
    
    public WorkTemplate WorkTemplateDataOnDemand.getNewTransientWorkTemplate(int index) {
        edu.unlv.cs.rebelhotel.domain.WorkTemplate obj = new edu.unlv.cs.rebelhotel.domain.WorkTemplate();
        obj.setName("name_" + index);
        obj.setHours(new Integer(index));
        obj.setTerm(null);
        return obj;
    }
    
    public WorkTemplate WorkTemplateDataOnDemand.getSpecificWorkTemplate(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        WorkTemplate obj = data.get(index);
        return WorkTemplate.findWorkTemplate(obj.getId());
    }
    
    public WorkTemplate WorkTemplateDataOnDemand.getRandomWorkTemplate() {
        init();
        WorkTemplate obj = data.get(rnd.nextInt(data.size()));
        return WorkTemplate.findWorkTemplate(obj.getId());
    }
    
    public boolean WorkTemplateDataOnDemand.modifyWorkTemplate(WorkTemplate obj) {
        return false;
    }
    
    public void WorkTemplateDataOnDemand.init() {
        data = edu.unlv.cs.rebelhotel.domain.WorkTemplate.findWorkTemplateEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'WorkTemplate' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.unlv.cs.rebelhotel.domain.WorkTemplate>();
        for (int i = 0; i < 10; i++) {
            edu.unlv.cs.rebelhotel.domain.WorkTemplate obj = getNewTransientWorkTemplate(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
