// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.WorkEffortDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkEffortIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkEffortIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkEffortIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: WorkEffortIntegrationTest: @Transactional;
    
    @Autowired
    private WorkEffortDataOnDemand WorkEffortIntegrationTest.dod;
    
    @Test
    public void WorkEffortIntegrationTest.testCountWorkEfforts() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to initialize correctly", dod.getRandomWorkEffort());
        long count = edu.unlv.cs.rebelhotel.domain.WorkEffort.countWorkEfforts();
        org.junit.Assert.assertTrue("Counter for 'WorkEffort' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkEffortIntegrationTest.testFindWorkEffort() {
        edu.unlv.cs.rebelhotel.domain.WorkEffort obj = dod.getRandomWorkEffort();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkEffort.findWorkEffort(id);
        org.junit.Assert.assertNotNull("Find method for 'WorkEffort' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'WorkEffort' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkEffortIntegrationTest.testFindAllWorkEfforts() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to initialize correctly", dod.getRandomWorkEffort());
        long count = edu.unlv.cs.rebelhotel.domain.WorkEffort.countWorkEfforts();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'WorkEffort', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<edu.unlv.cs.rebelhotel.domain.WorkEffort> result = edu.unlv.cs.rebelhotel.domain.WorkEffort.findAllWorkEfforts();
        org.junit.Assert.assertNotNull("Find all method for 'WorkEffort' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'WorkEffort' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkEffortIntegrationTest.testFindWorkEffortEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to initialize correctly", dod.getRandomWorkEffort());
        long count = edu.unlv.cs.rebelhotel.domain.WorkEffort.countWorkEfforts();
        if (count > 20) count = 20;
        java.util.List<edu.unlv.cs.rebelhotel.domain.WorkEffort> result = edu.unlv.cs.rebelhotel.domain.WorkEffort.findWorkEffortEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'WorkEffort' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'WorkEffort' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkEffortIntegrationTest.testFlush() {
        edu.unlv.cs.rebelhotel.domain.WorkEffort obj = dod.getRandomWorkEffort();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkEffort.findWorkEffort(id);
        org.junit.Assert.assertNotNull("Find method for 'WorkEffort' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkEffort(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'WorkEffort' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkEffortIntegrationTest.testMerge() {
        edu.unlv.cs.rebelhotel.domain.WorkEffort obj = dod.getRandomWorkEffort();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.WorkEffort.findWorkEffort(id);
        boolean modified =  dod.modifyWorkEffort(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.unlv.cs.rebelhotel.domain.WorkEffort merged = (edu.unlv.cs.rebelhotel.domain.WorkEffort) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'WorkEffort' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkEffortIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to initialize correctly", dod.getRandomWorkEffort());
        edu.unlv.cs.rebelhotel.domain.WorkEffort obj = dod.getNewTransientWorkEffort(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'WorkEffort' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'WorkEffort' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'WorkEffort' identifier to no longer be null", obj.getId());
    }
    
}
