package edu.unlv.cs.rebelhotel.domain.enums;

public enum Departments {

    /*HOSPITALITY_MANAGEMENT, 
    HOTEL_ADMINISTRATION_BEVERAGE_MANAGEMENT, 
    FOOD_SERVICE_MANAGEMENT, 
    LODGING_AND_RESORT_MANAGEMENT, 
    MEETINGS_AND_EVENTS_MANAGEMENT,
    CULINARY_ARTS_MANAGEMENT, 
    CULINARY_ARTS_BEVERAGE_MANAGEMENT,
    GAMING_MANAGEMENT,
    HOTEL_ADMINISTRATION_BEVERAGE_MANAGEMENT_PRE, 
    FOOD_SERVICE_MANAGEMENT_PRE, 
    LODGING_AND_RESORT_MANAGEMENT_PRE, 
    MEETINGS_AND_EVENTS_MANAGEMENT_PRE,
    CULINARY_ARTS_MANAGEMENT_PRE, 
    CULINARY_ARTS_BEVERAGE_MANAGEMENT_PRE,
    GAMING_MANAGEMENT_PRE;*/
	
    HOSSINBSMS, // HOSPITALITY_MANAGEMENT
    HOSBSHA,
    ENTMIN, // Entertainment Management Minor
    HBEVBSHA, //HOTEL_ADMINISTRATION_BEVERAGE_MANAGEMENT, 
    HBEVPRBSHA,
    FDMBSHA, //FOOD_SERVICE_MANAGEMENT, 
    FDMPRE,
    LRMBSHA, //LODGING_AND_RESORT_MANAGEMENT, 
    LRMPRE,
    MEMBSHA, //MEETINGS_AND_EVENTS_MANAGEMENT,
    MEMPRE,
    CAMBSCM, // CULINARY_ARTS_MANAGEMENT
    CAMPRE,
    CBEVBSCM, // CULINARY_ARTS_BEVERAGE_MANAGEMENT
    CBEVPRBSCM,
    GAMBSGM, // GAMING_MANAGEMENT
    GAMPRE,
    RECBS, // ignore
    RECMIN, // ignore
    RECPGMBS, // ignore
    SLSMSSLS; // graduate: Dual Master of Science in Management Information Systems/Master of Science in Hotel Administration
}
